### ISSUE TITLE
Feature Request: Add option to use a default key for OpenWeatherMap

### ISSUE THREAD

**Issue by rmeissn** [mozilla-iot/weather-adapter#15]
An API key is needed in each and every case for this addon. It would be handy to add a default key (with some restrictions, e.g. 1 API call per hour) to your application. I know that the gnome-shell extension openweather is providing a default key for OpenWeatherMap - https://gitlab.com/jenslody/gnome-shell-extension-openweather . I don't know whether they pay for it, but I guess they don't. Maybe they have some special API key or some other strategy to not run into the free limit of OpenWeatherMap. I guess you could ask the developer of the extension for details.

**Comment by mrstegeman** [comment]
Thanks for the suggestion! I've registered an API key associated for the project and have asked OpenWeatherMap to lift access restrictions for the key (which they seem to allow for FOSS applications). Hopefully I get an answer back soon.
