### ISSUE TITLE
Add Weather Underground to providers

### ISSUE THREAD

**Issue by LionMike** [mozilla-iot/weather-adapter#19]
I can create rules based on variables in my back yard rather than a location where conditions are different.

**Comment by mrstegeman** [comment]
It looks like Weather Underground only provides an API for contributors with their own personal weather stations.
1. I do not have one, so unless you want to provide me an API key, I can't test.
2. Wouldn't it be easier to just have an adapter that pulls data directly from the weather station?

**Comment by LionMike** [comment]
**1. I do not have one, so unless you want to provide me an API key, I can't test.** 
I can do that.

**2. Wouldn't it be easier to just have an adapter that pulls data directly from the weather station?**
How would that work?

**Comment by mrstegeman** [comment]
What weather station are you using? I'm just wondering if it might have a local API that we could query.

Could you email an API key to team@webthings.io? I will look at adding support next week.

**Comment by LionMike** [comment]
Acurite 5 in 1 with wifi.

**Comment by mrstegeman** [comment]
Ok, v0.6.0 has support for Weather Underground now, with some limitations:
* No support for cloud cover (not provided by API)
* No support for textual description (not provided by API)
* No support for raining/snowing (API provides a precipitation rate, but no way to tell what type)

**Comment by LionMike** [comment]
Works great! Thank You.
