### ISSUE TITLE
Adding cloud cover in percentage

### ISSUE THREAD

**Issue by Beejeedeb** [mozilla-iot/weather-adapter#7]
Hello,

I have added a cloud cover property bubble in the add-on. It was very easy to add. Copy and paste :-)

![cloud cover](https://user-images.githubusercontent.com/51539492/60769951-0f33a880-a0d6-11e9-8ce6-05335d238803.PNG)

The light meters that I have are located in a motion detector. The motion detectors are installed in rooms without direct daylight. A cloud cover percentage is therefore very useful for me until I have found a good waterproof z-wave light sensor for in the garden.

I only use OpenWeather, so I only tested it for that. For the other weather services I have added the data but have not tested it.

Shall I create a Pull Request for the changes I made or do you think this is not a good addition?

**Comment by mrstegeman** [comment]
That's great! Please submit a PR and I can test the other services for you.

**Comment by Beejeedeb** [comment]
Hi I am fairly new to GitHub and I am not a programmer, but can I make 1 PR with all the changed files? Now I have made several PR. Feels wrong.

**Comment by mrstegeman** [comment]
Yes, 1 PR with all changes is preferred. I did that for you and force-pushed to #8.
